/**
 * Who photographed each event card.
 *
 * GENERATED by `node scripts/fetch-event-photos.mjs`.
 *
 * The Pexels licence does not require attribution. This is here for the same
 * reason the portrait and vehicle credits are: the alternative is a set of
 * photographers whose work fronts a product and who are named nowhere in it.
 *
 * `alt` is the photographer's own description, kept verbatim. It is what the
 * picture actually shows — which, on a screen full of invented events, is the
 * only caption on the page that is true of the image.
 */
export interface EventCredit {
  photographer: string;
  photographerUrl: string;
  url: string;
  alt: string;
  /** The invented event this illustrates. */
  event: string;
}

export const EVENT_CREDITS: Record<string, EventCredit> = {
  "ev-anken-water-lantern": {
    photographer: "Quang Nguyen Vinh",
    photographerUrl: "https://www.pexels.com/@quang-nguyen-vinh-222549",
    url: "https://www.pexels.com/photo/women-on-wooden-boats-putting-paper-lanterns-on-water-14021519/",
    alt: "Peaceful scene of lantern-filled boats on a river at Hoi An Lantern Festival.",
    event: "安坑水燈漂流夜",
  },
  "ev-anping-lantern-shadow": {
    photographer: "Nguyễn Hoàng Văn",
    photographerUrl: "https://www.pexels.com/@valdemarvan",
    url: "https://www.pexels.com/photo/illuminated-red-lamps-over-street-19571465/",
    alt: "Charming city street illuminated by red lanterns at night.",
    event: "安平舊港燈影節",
  },
  "ev-bali-kite": {
    photographer: "Mike Norris",
    photographerUrl: "https://www.pexels.com/@miken",
    url: "https://www.pexels.com/photo/colorful-kite-flying-at-lytham-st-annes-beach-35664407/",
    alt: "Vibrant rainbow kite soaring at Lytham St Annes beach. Perfect day for kite flying.",
    event: "八里左岸風箏賽",
  },
  "ev-beinan-canoe": {
    photographer: "Daniel Ciubarov",
    photographerUrl: "https://www.pexels.com/@daniel-ciubarov-324306579",
    url: "https://www.pexels.com/photo/father-and-son-riding-a-kayak-on-the-river-13737937/",
    alt: "Two adults kayaking on a flowing river, enjoying outdoor leisure activities in summer.",
    event: "卑南溪獨木舟賽",
  },
  "ev-beitou-sulphur-walk": {
    photographer: "ROMAN ODINTSOV",
    photographerUrl: "https://www.pexels.com/@roman-odintsov",
    url: "https://www.pexels.com/photo/hot-soaring-stream-in-mountain-valley-4555535/",
    alt: "Hot soaring stream flowing over stones surrounded by hills with low grass at sunny day",
    event: "北投硫谷夜行",
  },
  "ev-bitan-market": {
    photographer: "J.D. Books",
    photographerUrl: "https://www.pexels.com/@j-d-books-554377679",
    url: "https://www.pexels.com/photo/vibrant-night-market-scene-with-stalls-and-lights-32977364/",
    alt: "Bustling night market with vibrant stalls, lights, and visitors enjoying the lively ambiance.",
    event: "碧潭河岸夏夜市集",
  },
  "ev-dadaocheng-riverdance": {
    photographer: "cole peters",
    photographerUrl: "https://www.pexels.com/@cole-peters-377317236",
    url: "https://www.pexels.com/photo/vibrant-night-party-under-string-lights-30505255/",
    alt: "Group of adults dancing energetically under string lights at night.",
    event: "大稻埕河岸夜舞",
  },
  "ev-dongshan-paper-lantern": {
    photographer: "浪 郭",
    photographerUrl: "https://www.pexels.com/@2150004161",
    url: "https://www.pexels.com/photo/glowing-lanterns-on-water-at-night-31108473/",
    alt: "Serene floating lanterns create a warm glow on the water at night.",
    event: "冬山河紙燈漂流夜",
  },
  "ev-gaomei-windmill-market": {
    photographer: "哲聖 林",
    photographerUrl: "https://www.pexels.com/@70588695",
    url: "https://www.pexels.com/photo/wind-turbines-behind-sea-shore-at-sunset-16646069/",
    alt: "A serene sunset over the coast with wind turbines silhouetted against the sky.",
    event: "高美風車市集",
  },
  "ev-gongguan-books": {
    photographer: "sonya zykova",
    photographerUrl: "https://www.pexels.com/@sonya-zykova-1135690651",
    url: "https://www.pexels.com/photo/street-stall-with-second-hand-books-22738054/",
    alt: "Vibrant collection of second-hand books displayed at a street stall in Moscow, Russia.",
    event: "公館舊書攤市集",
  },
  "ev-hualien-equestrian": {
    photographer: "Aliaksei Semirski",
    photographerUrl: "https://www.pexels.com/@asemirski",
    url: "https://www.pexels.com/photo/woman-riding-on-brown-horse-13814187/",
    alt: "Focused woman rider on horse during equestrian competition outdoors.",
    event: "縱谷馬術嘉年華",
  },
  "ev-liuchuan-brass": {
    photographer: "Anya  Juárez Tenorio",
    photographerUrl: "https://www.pexels.com/@anya-juarez-tenorio-227888521",
    url: "https://www.pexels.com/photo/street-parade-with-brass-band-performing-36193805/",
    alt: "A lively street parade featuring a brass band performing on a sunny day.",
    event: "綠川銅管音樂節",
  },
  "ev-love-river-lightboat": {
    photographer: "Syed Qaarif Andrabi",
    photographerUrl: "https://www.pexels.com/@qaarif",
    url: "https://www.pexels.com/photo/people-on-gondolas-at-night-11710969/",
    alt: "A vibrant night scene of decorated boats illuminating a river during a traditional festival.",
    event: "愛河夜航燈船",
  },
  "ev-maokong-tea-night": {
    photographer: "Duc Nguyen",
    photographerUrl: "https://www.pexels.com/@duc-nguyen-2149183346",
    url: "https://www.pexels.com/photo/lush-green-tea-plantations-in-misty-hills-33437258/",
    alt: "A serene view of green tea plantations on misty hills, creating a tranquil landscape.",
    event: "貓空秋茶夜宴",
  },
  "ev-qixingtan-starlight": {
    photographer: "Dominiquemel16 Ramos",
    photographerUrl: "https://www.pexels.com/@dominiquemel",
    url: "https://www.pexels.com/photo/street-musicians-performing-with-string-instruments-37947679/",
    alt: "Four street musicians playing string instruments outdoors, creating a lively scene.",
    event: "七星潭星空音樂會",
  },
  "ev-wulai-valley-song": {
    photographer: "Bence Szemerey",
    photographerUrl: "https://www.pexels.com/@bence-szemerey-337043",
    url: "https://www.pexels.com/photo/aerial-footage-of-live-concert-7081216/",
    alt: "Vibrant outdoor concert scene with a lively crowd in Budapest during dusk.",
    event: "烏來溪谷歌謠祭",
  },
  "ev-wutiaogang-night-patrol": {
    photographer: "Jimmy Liao",
    photographerUrl: "https://www.pexels.com/@jimmy-liao-3615017",
    url: "https://www.pexels.com/photo/people-walking-in-a-parade-on-the-city-street-during-a-celebration-19272751/",
    alt: "A colorful and lively street festival in Taipei, Taiwan, featuring traditional costumes, lanterns, and crowds.",
    event: "五條港夜巡",
  },
};

export const eventCredit = (id: string): EventCredit | undefined => EVENT_CREDITS[id];
