/**
 * Which events have a picture on disk.
 *
 * GENERATED by `node scripts/fetch-event-photos.mjs`. Do not hand-edit: an id
 * in here without a file behind it is a broken image on a card.
 *
 * None of these is a photograph of the event it sits on — the events are
 * invented, so no such photograph exists. They are stock images of the kind of
 * evening each record describes, which is why `EventImage` puts the 示意 mark
 * on the picture itself rather than trusting a line at the foot of the page.
 */
export const EVENT_PHOTO_IDS: ReadonlySet<string> = new Set([
  "ev-anken-water-lantern",
  "ev-anping-lantern-shadow",
  "ev-bali-kite",
  "ev-beinan-canoe",
  "ev-beitou-sulphur-walk",
  "ev-bitan-market",
  "ev-dadaocheng-riverdance",
  "ev-dongshan-paper-lantern",
  "ev-gaomei-windmill-market",
  "ev-gongguan-books",
  "ev-hualien-equestrian",
  "ev-liuchuan-brass",
  "ev-love-river-lightboat",
  "ev-maokong-tea-night",
  "ev-qixingtan-starlight",
  "ev-wulai-valley-song",
  "ev-wutiaogang-night-patrol",
]);

export const hasEventPhoto = (id: string) => EVENT_PHOTO_IDS.has(id);
