/**
 * Who photographed each driver and guide.
 *
 * GENERATED by `node scripts/fetch-stock-portraits.mjs`.
 *
 * The Pexels licence does not require attribution. This is here anyway, because
 * the alternative is forty photographers whose work fronts a product and who are
 * named nowhere in it — and because the promise to credit them was made when the
 * key was asked for.
 *
 * These are stock photographs of models who signed a release permitting exactly
 * this use. They are not the actual service providers, which is what the mark on
 * the image and the line at the foot of every list both say.
 */
export interface PortraitCredit {
  photographer: string;
  photographerUrl: string;
  /** The listing on Pexels, for anybody who wants the original. */
  url: string;
}

export const PORTRAIT_CREDITS: Record<string, PortraitCredit> = {
  /* 阿誠包車旅遊 */
  "p-acheng": {
    photographer: "Wasin Pirom",
    photographerUrl: "https://www.pexels.com/@wasinpirom",
    url: "https://www.pexels.com/photo/confident-asian-man-in-grey-shirt-saluting-31465733/",
  },
  /* 小芳包車旅遊 */
  "p-xiaofang": {
    photographer: "Kevin  Malik",
    photographerUrl: "https://www.pexels.com/@kevin-malik",
    url: "https://www.pexels.com/photo/woman-in-black-top-clenching-fists-9017016/",
  },
  /* 大熊旅遊包車 */
  "p-dabear": {
    photographer: "Ketut Subiyanto",
    photographerUrl: "https://www.pexels.com/@ketut-subiyanto",
    url: "https://www.pexels.com/photo/man-in-blue-denim-top-pointing-finger-up-4584185/",
  },
  /* 府城包車小旅行 */
  "p-fucheng-car": {
    photographer: "Vitaly Gariev",
    photographerUrl: "https://www.pexels.com/@silverkblack",
    url: "https://www.pexels.com/photo/smiling-man-in-casual-checkered-shirt-portrait-36764485/",
  },
  /* 花蓮山海包車 */
  "p-hualien-car": {
    photographer: "Andres  Ayrton",
    photographerUrl: "https://www.pexels.com/@andres-ayrton",
    url: "https://www.pexels.com/photo/content-asian-man-with-green-apple-6550807/",
  },
  /* 阿凱代駕 */
  "p-akai": {
    photographer: "SHVETS production",
    photographerUrl: "https://www.pexels.com/@shvets-production",
    url: "https://www.pexels.com/photo/a-man-in-hoodie-sweater-smiling-9775538/",
  },
  /* 小米 */
  "p-xiaomi": {
    photographer: "RDNE Stock project",
    photographerUrl: "https://www.pexels.com/@rdne",
    url: "https://www.pexels.com/photo/woman-in-black-clothes-holding-a-document-binder-folder-7845034/",
  },
  /* 阿哲 */
  "p-azhe": {
    photographer: "Andrea Piacquadio",
    photographerUrl: "https://www.pexels.com/@olly",
    url: "https://www.pexels.com/photo/man-in-gray-crew-neck-shirt-smiling-3761521/",
  },
  /* Ada */
  "p-ada": {
    photographer: "Felix Young",
    photographerUrl: "https://www.pexels.com/@felix-young-449360607",
    url: "https://www.pexels.com/photo/asian-woman-sitting-on-large-decorative-flower-30944872/",
  },
  /* 秀珠 */
  "p-tainan-guide": {
    photographer: "Centre for Ageing Better",
    photographerUrl: "https://www.pexels.com/@centre-for-ageing-better-55954677",
    url: "https://www.pexels.com/photo/woman-with-purple-hair-13804486/",
  },
  /* Panay */
  "p-hualien-guide": {
    photographer: "Quý Nguyễn",
    photographerUrl: "https://www.pexels.com/@chupanhchandung",
    url: "https://www.pexels.com/photo/smiling-woman-in-polo-shirt-17253005/",
  },
  /* 瑞芳山線包車 */
  "p-ruifang-car": {
    photographer: "宇峰 吳",
    photographerUrl: "https://www.pexels.com/@fungfung852",
    url: "https://www.pexels.com/photo/portrait-of-a-man-in-a-fur-coat-6244521/",
  },
  /* 阿源 */
  "p-jiufen-guide": {
    photographer: "Ketut Subiyanto",
    photographerUrl: "https://www.pexels.com/@ketut-subiyanto",
    url: "https://www.pexels.com/photo/man-in-blue-top-pointing-finger-on-forehead-4584178/",
  },
  /* 淡水海線包車 */
  "p-tamsui-car": {
    photographer: "Vitaly Gariev",
    photographerUrl: "https://www.pexels.com/@silverkblack",
    url: "https://www.pexels.com/photo/portrait-of-mature-man-in-checkered-shirt-36764484/",
  },
  /* 怡君 */
  "p-tamsui-guide": {
    photographer: "Đức Trung Đào",
    photographerUrl: "https://www.pexels.com/@macnalodao",
    url: "https://www.pexels.com/photo/smiling-woman-with-long-black-hair-17644066/",
  },
  /* 台中山海線包車 */
  "p-taichung-car": {
    photographer: "Hao Peng",
    photographerUrl: "https://www.pexels.com/@hao-peng-2148478861",
    url: "https://www.pexels.com/photo/portrait-of-a-man-wearing-glasses-in-studio-30976000/",
  },
  /* 宗翰 */
  "p-taichung-guide": {
    photographer: "Pro5 vn",
    photographerUrl: "https://www.pexels.com/@pro5-vn-1368185933",
    url: "https://www.pexels.com/photo/portrait-of-man-sitting-and-smiling-in-jacket-on-gray-background-25884721/",
  },
  /* 港都包車 */
  "p-kaohsiung-car": {
    photographer: "Wasin Pirom",
    photographerUrl: "https://www.pexels.com/@wasinpirom",
    url: "https://www.pexels.com/photo/man-standing-with-tablet-16692396/",
  },
  /* 淑玲 */
  "p-kaohsiung-guide": {
    photographer: "PROFFESIONAL PHOTO STOCK",
    photographerUrl: "https://www.pexels.com/@proffesional-photo-stock-2153424730",
    url: "https://www.pexels.com/photo/professional-asian-woman-in-corporate-attire-37830403/",
  },
  /* 蘭陽平原包車 */
  "p-jiaoxi-car": {
    photographer: "HONG SON",
    photographerUrl: "https://www.pexels.com/@hson",
    url: "https://www.pexels.com/photo/portrait-of-a-smiling-senior-man-outdoors-32975143/",
  },
  /* 文彥 */
  "p-jiaoxi-guide": {
    photographer: "MENG MEDIA",
    photographerUrl: "https://www.pexels.com/@mengmedia",
    url: "https://www.pexels.com/photo/a-man-in-a-blue-suit-10919461/",
  },
  /* 佩瑜 */
  "p-luodong-guide": {
    photographer: "Darina Belonogova",
    photographerUrl: "https://www.pexels.com/@darina-belonogova",
    url: "https://www.pexels.com/photo/woman-in-green-tank-top-8789450/",
  },
  /* 縱谷海線包車 */
  "p-taitung-car": {
    photographer: "Kampus Production",
    photographerUrl: "https://www.pexels.com/@kampus",
    url: "https://www.pexels.com/photo/close-up-shot-of-a-man-wearing-his-red-sweater-7417149/",
  },
  /* Sawagu */
  "p-taitung-guide": {
    photographer: "Sóc Năng Động",
    photographerUrl: "https://www.pexels.com/@soc-nang-d-ng-2150345854",
    url: "https://www.pexels.com/photo/portrait-of-a-thoughtful-man-in-outdoor-setting-38620726/",
  },
  /* 郁婷 */
  "p-hualien-city-guide": {
    photographer: "Michelangelo Buonarroti",
    photographerUrl: "https://www.pexels.com/@michelangelo-buonarroti",
    url: "https://www.pexels.com/photo/woman-in-white-blazer-holding-a-glass-8728101/",
  },
  /* 池上縱谷小巴 */
  "p-chishang-car": {
    photographer: "Ketut Subiyanto",
    photographerUrl: "https://www.pexels.com/@ketut-subiyanto",
    url: "https://www.pexels.com/photo/a-smiling-man-in-beige-crew-neck-t-shirt-4584548/",
  },
  /* 秀蘭 */
  "p-chishang-guide": {
    photographer: "Thể Phạm",
    photographerUrl: "https://www.pexels.com/@phamthe",
    url: "https://www.pexels.com/photo/woman-posing-in-a-yellow-dress-21847521/",
  },
  /* 東海岸包車 */
  "p-chenggong-car": {
    photographer: "Sóc Năng Động",
    photographerUrl: "https://www.pexels.com/@soc-nang-d-ng-2150345854",
    url: "https://www.pexels.com/photo/portrait-of-a-thoughtful-man-in-outdoor-setting-38620726/",
  },
  /* Ina */
  "p-chenggong-guide": {
    photographer: "yi lu",
    photographerUrl: "https://www.pexels.com/@luyi",
    url: "https://www.pexels.com/photo/close-up-photo-of-woman-smiling-11563145/",
  },
  /* 馬太鞍包車 */
  "p-guangfu-car": {
    photographer: "PNW Production",
    photographerUrl: "https://www.pexels.com/@pnw-prod",
    url: "https://www.pexels.com/photo/a-man-wearing-black-sweater-8250095/",
  },
  /* Lisin */
  "p-guangfu-guide": {
    photographer: "Mikhail Nilov",
    photographerUrl: "https://www.pexels.com/@mikhail-nilov",
    url: "https://www.pexels.com/photo/a-woman-wearing-dress-8872782/",
  },
  /* 太魯閣峽谷接駁 */
  "p-taroko-car": {
    photographer: "HONG SON",
    photographerUrl: "https://www.pexels.com/@hson",
    url: "https://www.pexels.com/photo/man-in-blue-polo-shirt-12488270/",
  },
  /* 北海岸包車 */
  "p-yehliu-car": {
    photographer: "Lê Hướng",
    photographerUrl: "https://www.pexels.com/@le-h-ng-2231862",
    url: "https://www.pexels.com/photo/woman-holding-on-handrails-5435032/",
  },
  /* 建良 */
  "p-yehliu-guide": {
    photographer: "Theodore Nguyen",
    photographerUrl: "https://www.pexels.com/@thejourneyofframes",
    url: "https://www.pexels.com/photo/portrait-of-man-wearing-black-shirt-25863044/",
  },
  /* 俊宏 */
  "p-pingxi-guide": {
    photographer: "Gustavo Fring",
    photographerUrl: "https://www.pexels.com/@gustavo-fring",
    url: "https://www.pexels.com/photo/man-in-white-shirt-smiling-widely-5622689/",
  },
  /* 台中海線包車 */
  "p-qingshui-car": {
    photographer: "Dany Kurniawan",
    photographerUrl: "https://www.pexels.com/@danykurstudio",
    url: "https://www.pexels.com/photo/a-man-using-megaphone-12357432/",
  },
  /* 雅萍 */
  "p-gaomei-guide": {
    photographer: "https://kaboompics.com/",
    photographerUrl: "https://www.pexels.com/@karola-g",
    url: "https://www.pexels.com/photo/woman-wearing-baby-blue-long-sleeve-shirt-8555640/",
  },
  /* 羅東冬山包車 */
  "p-luodong-car": {
    photographer: "cottonbro studio",
    photographerUrl: "https://www.pexels.com/@cottonbro",
    url: "https://www.pexels.com/photo/a-woman-eating-cereal-6150651/",
  },
  /* 新城海線接送 */
  "p-qixingtan-car": {
    photographer: "Duy's  House of Photo",
    photographerUrl: "https://www.pexels.com/@duy-s-house-of-photo-2150454349",
    url: "https://www.pexels.com/photo/professional-portrait-of-a-businessman-in-studio-31268616/",
  },
  /* 美玲 */
  "p-qixingtan-guide": {
    photographer: "거열 박",
    photographerUrl: "https://www.pexels.com/@geoyul",
    url: "https://www.pexels.com/photo/a-beautiful-woman-in-orange-top-and-a-white-skirt-9579141/",
  },
};

export const portraitCredit = (providerId: string): PortraitCredit | undefined =>
  PORTRAIT_CREDITS[providerId];
