/**
 * Which drivers and guides have a portrait on disk.
 *
 * GENERATED by `node scripts/build-portraits.mjs`. Drop a file into
 * `.portrait-src/` named after the provider id and run it again — do not
 * hand-edit this list, because an id in here without a file behind it is a
 * broken image on a card.
 *
 * A manifest rather than a field on each `Provider`: the record describes the
 * person, and whether a picture has been produced yet is a fact about the
 * repository. Keeping it here means a portrait arriving is a one-line diff in a
 * generated file instead of a hand edit to 40 data records — and it means the
 * app never requests a file that is not there, which is the difference between
 * a designed placeholder and a 404 behind every card.
 *
 * Every one of these is an AI-generated illustration of a person who does not
 * exist, which is why `PersonPhoto` puts a mark on the image itself rather than
 * a line at the bottom of the page. A photograph of a face is the one thing in
 * this demo a viewer would otherwise assume is real.
 *
 * Prompts: PORTRAIT_PROMPTS.md.
 */
export const PORTRAIT_IDS: ReadonlySet<string> = new Set([
  "p-acheng",
  "p-jiufen-guide",
  "p-tainan-guide",
  "p-xiaofang",
]);

export const hasPortrait = (providerId: string) => PORTRAIT_IDS.has(providerId);
