/**
 * Who photographed each hire car.
 *
 * GENERATED by `node scripts/fetch-stock-vehicles.mjs`.
 *
 * The Pexels licence does not require attribution. This is here anyway, for the
 * same reason the portrait credits are: the alternative is twenty-two
 * photographers whose work fronts a product and who are named nowhere in it.
 *
 * None of these is a photograph of the counter it appears on. They are stock
 * photographs of the class of car each record offers — which is a fact the card
 * already states in its own 車型 row, and the most a stock library can honestly
 * illustrate. The mark on the image and the line on the detail page both say so.
 */
export interface VehicleCredit {
  photographer: string;
  photographerUrl: string;
  /** The listing on Pexels, for anybody who wants the original. */
  url: string;
  /** The class of car this illustrates — the same string the card's 車型 row
      shows, so the credit can name what the picture is a picture OF. */
  model: string;
}

export const VEHICLE_CREDITS: Record<string, VehicleCredit> = {
  /* 格上租車 板橋車站營業所 */
  "r-carplus-banqiao": {
    photographer: "FurtherMore Studio",
    photographerUrl: "https://www.pexels.com/@bobo",
    url: "https://www.pexels.com/photo/blue-compact-suv-parked-on-urban-street-31501638/",
    model: "Toyota Corolla Cross",
  },
  /* 格上租車 花蓮車站 國聯五路營業所 */
  "r-carplus-hualien": {
    photographer: "Yazid N",
    photographerUrl: "https://www.pexels.com/@mzynasx",
    url: "https://www.pexels.com/photo/white-minivan-parked-at-modern-airport-terminal-39075475/",
    model: "Toyota Sienta",
  },
  /* 格上租車 台南車站前營業所 */
  "r-carplus-tainan": {
    photographer: "Erik Mclean",
    photographerUrl: "https://www.pexels.com/@introspectivedsgn",
    url: "https://www.pexels.com/photo/a-side-view-of-a-parked-red-vehicle-13767773/",
    model: "Nissan Kicks",
  },
  /* 格上租車 信義區 松仁路營業所 */
  "r-carplus-taipei-xinyi": {
    photographer: "FurtherMore Studio",
    photographerUrl: "https://www.pexels.com/@bobo",
    url: "https://www.pexels.com/photo/blue-compact-suv-parked-outdoors-for-lifestyle-use-32462525/",
    model: "Nissan Kicks",
  },
  /* 格上租車 宜蘭車站營業所 */
  "r-carplus-yilan": {
    photographer: "Stephen Andrews",
    photographerUrl: "https://www.pexels.com/@stephentcandrews",
    url: "https://www.pexels.com/photo/a-blue-toyota-rav4-9615358/",
    model: "Toyota Corolla Cross",
  },
  /* 和運租車 花蓮車站營業所 */
  "r-easyrent-hualien": {
    photographer: "Kadir Akman",
    photographerUrl: "https://www.pexels.com/@kadirakman",
    url: "https://www.pexels.com/photo/silver-sedan-parked-beside-brown-brick-wall-11501948/",
    model: "Toyota Altis",
  },
  /* 和運租車 高雄車站營業所 */
  "r-easyrent-kaohsiung": {
    photographer: "Erik Mclean",
    photographerUrl: "https://www.pexels.com/@introspectivedsgn",
    url: "https://www.pexels.com/photo/the-white-2020-toyota-highlander-parked-in-front-of-a-brick-wall-27497572/",
    model: "Toyota RAV4",
  },
  /* 和運租車 水社遊客中心旁 中山路 */
  "r-easyrent-sunmoonlake": {
    photographer: "dumitru B",
    photographerUrl: "https://www.pexels.com/@dumitru-b-742240889",
    url: "https://www.pexels.com/photo/silver-sedan-parked-by-coastal-road-28884174/",
    model: "Toyota Altis",
  },
  /* 和運租車 台中車站營業所 */
  "r-easyrent-taichung": {
    photographer: "Siddant Kanthi",
    photographerUrl: "https://www.pexels.com/@siddant-kanthi-1648343429",
    url: "https://www.pexels.com/photo/white-suv-parked-under-trees-in-sunny-lot-29477633/",
    model: "Toyota Corolla Cross",
  },
  /* 和運租車 台北車站 館前路營業所 */
  "r-easyrent-taipei-main": {
    photographer: "Andrey Andname",
    photographerUrl: "https://www.pexels.com/@andname",
    url: "https://www.pexels.com/photo/side-view-of-a-parked-white-suv-4909544/",
    model: "Toyota RAV4",
  },
  /* 和運租車 台東車站營業所 */
  "r-easyrent-taitung": {
    photographer: "Oli Liao",
    photographerUrl: "https://www.pexels.com/@oli-liao-883836674",
    url: "https://www.pexels.com/photo/sleek-black-sedan-parked-in-urban-setting-35628774/",
    model: "Toyota Altis",
  },
  /* iRent 花蓮車站前 國聯一路 */
  "r-irent-hualien": {
    photographer: "Kostiantyn Zavhorodnii",
    photographerUrl: "https://www.pexels.com/@kostiantyn-zavhorodnii-637657209",
    url: "https://www.pexels.com/photo/sleek-black-hatchback-car-in-parking-lot-33326195/",
    model: "Toyota Yaris",
  },
  /* iRent 高雄車站 南華路停車場 */
  "r-irent-kaohsiung": {
    photographer: "CAMCAT Christopher Michael",
    photographerUrl: "https://www.pexels.com/@camcat",
    url: "https://www.pexels.com/photo/time-lapse-photo-of-a-minivan-11336600/",
    model: "Toyota Sienta",
  },
  /* iRent 台中車站 建國路停車場 */
  "r-irent-taichung": {
    photographer: "İsmail ERTAN",
    photographerUrl: "https://www.pexels.com/@i-smail-ertan-2156193902",
    url: "https://www.pexels.com/photo/gray-toyota-auris-in-scenic-outdoor-setting-35016609/",
    model: "Toyota Yaris",
  },
  /* iRent 台南車站 北門路停車場 */
  "r-irent-tainan": {
    photographer: "Erik Mclean",
    photographerUrl: "https://www.pexels.com/@introspectivedsgn",
    url: "https://www.pexels.com/photo/blue-car-parked-near-wall-5199497/",
    model: "Toyota Yaris",
  },
  /* iRent 台北車站 北平西路停車場 */
  "r-irent-taipei-main": {
    photographer: "Mike Bird",
    photographerUrl: "https://www.pexels.com/@mikebird",
    url: "https://www.pexels.com/photo/a-red-car-parked-on-dirt-road-7744713/",
    model: "Toyota Yaris",
  },
  /* iRent 新店中正路 路邊租還點 */
  "r-irent-xindian": {
    photographer: "Thang Nguyen",
    photographerUrl: "https://www.pexels.com/@chipi1189",
    url: "https://www.pexels.com/photo/silver-mpv-driving-down-tree-lined-urban-street-37029578/",
    model: "Toyota Sienta",
  },
  /* iRent 礁溪車站前 溫泉路 */
  "r-irent-yilan": {
    photographer: "Mike Bird",
    photographerUrl: "https://www.pexels.com/@mikebird",
    url: "https://www.pexels.com/photo/a-car-parked-outdoors-20303898/",
    model: "Toyota Yaris",
  },
  /* KKday 租車 花蓮車站周邊多家門市 */
  "r-kkday-hualien": {
    photographer: "Tom Fisk",
    photographerUrl: "https://www.pexels.com/@tomfisk",
    url: "https://www.pexels.com/photo/rows-of-parked-cars-3856436/",
    model: "小型車 起",
  },
  /* Klook 租車 台北車站周邊多家門市 */
  "r-klook-taipei": {
    photographer: "Renato Rocca",
    photographerUrl: "https://www.pexels.com/@renato-rocca-2397962",
    url: "https://www.pexels.com/photo/colorful-parked-cars-5800943/",
    model: "小型車 起",
  },
  /* Klook 租車 台東車站周邊多家門市 */
  "r-klook-taitung": {
    photographer: "Luke Miller",
    photographerUrl: "https://www.pexels.com/@bylukemiller",
    url: "https://www.pexels.com/photo/row-of-cars-parked-in-an-urban-parking-lot-29566909/",
    model: "小型車 起",
  },
  /* Trip.com 租車 水社碼頭周邊門市 */
  "r-trip-sunmoonlake": {
    photographer: "Pixabay",
    photographerUrl: "https://www.pexels.com/@pixabay",
    url: "https://www.pexels.com/photo/mercedes-benz-parked-in-a-row-164634/",
    model: "小型車 起",
  },
};

export const vehicleCredit = (rentalId: string): VehicleCredit | undefined =>
  VEHICLE_CREDITS[rentalId];
