/**
 * Which hire counters have a vehicle photograph on disk.
 *
 * GENERATED by `node scripts/fetch-stock-vehicles.mjs`. Do not hand-edit: an id
 * in here without a file behind it is a broken image on a card.
 *
 * A manifest rather than a field on each `CarRental`: the record describes the
 * counter, and whether a picture has been fetched yet is a fact about the
 * repository. It also means the app never requests a file that is not there,
 * which is the difference between a designed fallback and a 404.
 *
 * None of these is a photograph of the counter it sits on — they are stock
 * photographs of the class of car the record offers. That is why `VehiclePhoto`
 * puts a mark on the image itself rather than a line at the foot of the page.
 */
export const VEHICLE_IDS: ReadonlySet<string> = new Set([
  "r-carplus-banqiao",
  "r-carplus-hualien",
  "r-carplus-tainan",
  "r-carplus-taipei-xinyi",
  "r-carplus-yilan",
  "r-easyrent-hualien",
  "r-easyrent-kaohsiung",
  "r-easyrent-sunmoonlake",
  "r-easyrent-taichung",
  "r-easyrent-taipei-main",
  "r-easyrent-taitung",
  "r-irent-hualien",
  "r-irent-kaohsiung",
  "r-irent-taichung",
  "r-irent-tainan",
  "r-irent-taipei-main",
  "r-irent-xindian",
  "r-irent-yilan",
  "r-kkday-hualien",
  "r-klook-taipei",
  "r-klook-taitung",
  "r-trip-sunmoonlake",
]);

export const hasVehiclePhoto = (rentalId: string) => VEHICLE_IDS.has(rentalId);
